name = "Ice Age"
author = "crow-maki"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d4bca7081a231ecfd3b04d63068c27128f2894e88301fa3a5a5e20569b6ee1d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
